# Generated by Django 4.1.7 on 2023-03-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='psc',
            new_name='zip',
        ),
    ]
