# Generated by Django 4.1.7 on 2023-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expotoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expotoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
