# Generated by Django 4.1.7 on 2023-03-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_offerchatusers_offerchat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerchatusers',
            name='offer_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_chats', to='core.offerchat'),
        ),
    ]
