# Generated by Django 4.1.7 on 2023-04-25 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_offerchatusers_offerchat_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferChatUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.BooleanField(default=False)),
                ('offer_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_users', to='core.offerchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_chat_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offers_chats_users',
                'default_permissions': (),
            },
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_coordinates',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_string',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=200, null=True, verbose_name='message_content'),
        ),
        migrations.DeleteModel(
            name='OfferChatUsers',
        ),
    ]
