# Generated by Django 4.1.7 on 2023-04-25 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_offerchatusers_offer_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_coordinates',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_string',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=200, null=True, verbose_name='message_content'),
        ),
        migrations.DeleteModel(
            name='OfferChatUsers',
        ),
    ]
